language: node_js
node_js:
  - "6"

sudo: false

branch:
  only:
    - master

before_script:
  - npm run test:lint
  - node_modules/.bin/karma start karma.conf.js --auto-watch --single-run --reporters progress

script:
 - npm run compile
