language: node_js
node_js:
  - "6"
  - "6.1"

sudo: false

branch:
  only:
    - master

script:
  - node_modules/.bin/karma start karma.conf.js --auto-watch --single-run --reporters karma-phantomjs-launcher
